server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:5001/macrozhengmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sbt123

mybatis:
  mapper-locations:
    - classpath: mapper/*.xml


